instagram_clone/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('accounts/', views.profile, name='profile'),
    path('index/<int:user_idx>', views.index, name='index'),
    path('', views.profile, name='profile'),
    
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
    path('upload_img/<int:user_idx>', views.upload_img, name='upload_img'),
    path('delete_img/<int:user_idx>', views.delete_img, name='delete_img'),
    path('profile/<int:user_idx>', views.profile, name='profile'),
    path('change_pw/<int:user_idx>', views.change_pw, name='change_pw'),
   
    path('search/', views.search, name='search'),
    path('follow/<int:user_idx>', views.follow, name='follow'),
]

instagram_clone/notifications/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.notifications, name='notifications'),
]

instagram_clone/posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),
    
    path('create/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    
    path('detail/<int:pk>', views.detail, name='detail'),
    path('like/<int:post_id>/', views.post_like, name='post_like'),
    
    path('delete_comment/<int:post_id>/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('create_comment/<int:pk>', views.create_comment, name='create_comment'),
    path('edit_comment/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('user_posts/', views.user_posts, name='user_posts'),
]

instagram_clone/stories/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'stories'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('story_delete/<int:pk>/', views.story_delete, name='story_delete'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('archive/', views.archive, name='archive'),
]

instagram_clone/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Clone</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script><script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src='https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js'></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="grid-container">
        {% block navbar %}
        <div id="navbar-section" class="grid-item">
            <img src="{% static "images/posts/logo.png" %}" width=100px alt="logo"><br>

            <a class="btn btn-light text-decoration-none text-start" href="{% url 'posts:home' %}" class="icon-text"> <!-- Home -->
                <img src="{% static "images/posts/home.png" %}" class="icon" alt="home">
                <span class="text">홈</span></span>
            </a>
            <br>
            <a class="btn btn-light text-decoration-none text-start" href="{% url 'accounts:search' %}" class="icon-text"> <!-- Search -->
                <img src="{% static "images/posts/search.png" %}" class="icon" alt="search">
                <span class="text">검색</span>
            </a>
            <br>
            <a class="btn btn-light text-decoration-none text-start" href="#" class="icon-text"> <!-- Messages -->
                <img src="{% static "images/posts/messages.png" %}" class="icon" alt="messages">
                <span class="text">메시지</span>
            </a>
            <br>
            <a class="btn btn-light text-decoration-none text-start" href={% url "notifications:notifications" %} class="icon-text"> <!-- Notifications -->
                <img src="{% static "images/posts/notifications.png" %}" class="icon" alt="notifications">
                <span class="text">알림</span>
            </a>
            <br>
            <!-- 모달 열기 버튼 -->
            <button type="button" id='btn-primary' class="btn btn-light text-decoration-none text-start" data-toggle="modal" data-target="#BaseModalCenter"><!-- Create -->
                <img src="{% static "images/posts/create.png" %}" class="icon" alt="create">
                <span class="text">만들기</span>
            </button>

            <!-- 모달 창 변경 (최희정)-->
              <!-- Modal -->
            <div class="modal fade" id="BaseModalCenter" tabindex="-1" role="dialog" aria-labelledby="BaseModalCenterTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">작성 선택</h5>
                    </div>

                    <div class="modal-footer">
                    <a href="{% url 'posts:create' %}" class="btn btn-primary text-decoration-none">게시글 올리기</a>
                    <a href="{% url 'stories:create' %}" class="btn btn-primary text-decoration-none">스토리 올리기</a>
                    <button type="button" id='close' class="btn btn-secondary" data-dismiss="modal">닫기</button>
                    </div>
                </div>
                </div>
            </div>

            <!-- 모달 창 -->

            <br>
            <a class="btn btn-light text-decoration-none text-start" href="{% url 'accounts:index' user_idx=request.user.id %}" class="icon-text"> <!-- Profile -->

                <img src="{% static "images/posts/avatar.png" %}" class="icon" alt="profile">
                <span class="text">프로필</span>
            </a>
        </div>
        {% endblock navbar %}
        <div id="main-section" class="grid-item">
        {% block content %}
        {% endblock content %}
        </div>

    </div>    


    {% block logincontent %}
    {% endblock logincontent %}

    <script>


        // Launch demo modal 버튼을 클릭했을 때 실행되는 함수
        document.querySelector('#btn-primary').addEventListener('click', function() {
            // 모달을 표시하는 부트스트랩의 modal 메서드 호출
            $('#BaseModalCenter').modal('show');
        });

        // close 버튼을 클릭했을 때 실행되는 함수
        document.querySelector('#close').addEventListener('click', function() {
            // 모달을 닫는 부트스트랩의 modal 메서드 호출
            $('#BaseModalCenter').modal('hide');
        });

    </script>
    

    {% block script %}
    {% endblock script %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>