instagram_clone/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('accounts/', views.profile, name='profile'),
    path('index/<int:user_idx>', views.index, name='index'),
    path('', views.profile, name='profile'),
    
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
    path('upload_img/<int:user_idx>', views.upload_img, name='upload_img'),
    path('delete_img/<int:user_idx>', views.delete_img, name='delete_img'),
    path('profile/<int:user_idx>', views.profile, name='profile'),
    path('change_pw/<int:user_idx>', views.change_pw, name='change_pw'),
   
    path('search/', views.search, name='search'),
    path('follow/<int:user_idx>', views.follow, name='follow'),
]

instagram_clone/posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),
    
    path('create/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    
    path('detail/<int:pk>', views.detail, name='detail'),
    path('like/<int:post_id>/', views.post_like, name='post_like'),
    
    path('delete_comment/<int:post_id>/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('create_comment/<int:pk>', views.create_comment, name='create_comment'),
    path('edit_comment/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('user_posts/', views.user_posts, name='user_posts'),
]

instagram_clone/stories/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'stories'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('story_delete/<int:pk>/', views.story_delete, name='story_delete'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('archive/', views.archive, name='archive'),
]

instagram_clone/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django import forms

# Create your models here.
class User(AbstractUser):
    gender_choices = (
        ('M', '남성'),
        ('F', '여성'),
        ('O', '선택안함'),
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    

    alias_name = models.CharField(max_length=100)
    real_name = models.CharField(max_length=100)
    
    username = models.CharField(max_length=100, unique=True)
    introduce = models.TextField(max_length=100)
    gender = models.CharField(max_length=1, choices=gender_choices, default='O')
    is_notify = models.BooleanField(default = True)
    followings = models.ManyToManyField("self", symmetrical=False, related_name="followers")
    profile_url = models.TextField(default='')
    profile_img_name = models.CharField(max_length=100, default='')

instagram_clone/accounts/forms.py
from typing import Any
from django.db import models

from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from django import forms

class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['password1'].help_text = '' # "<br>6자리 이상, 숫자/문자/기호문자 포함해주세요"
        self.fields['password1'].widget = forms.TextInput(attrs={'id':'password1', 'type':'password', 'placeholder': '6자리 이상, 숫자/문자/기호문자 포함해주세요','class': 'placeholder-message'})
        self.fields['password1'].label = ''
        del self.fields['password2']


    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        # 'profile_img', email
        # fields = ('username', 'alias_name', 'real_name','introduce', 'gender', 'is_notify')
        fields = ('username', 'alias_name', 'real_name', 'password1')
      
        widgets = {
            'real_name':forms.TextInput(attrs={"placeholder" : "성명을 입력하세요", 'class': 'placeholder-message'}),
            'alias_name':forms.TextInput(attrs={"placeholder" : "사용자 이름을 입력하세요", 'class': 'placeholder-message'}),
            'username': forms.TextInput(attrs={'placeholder':'핸드폰번호나 이메일을 입력해주세요', 'class': 'placeholder-message'}),
        }
        labels = {
            'username' : '',
            'real_name' : '',
            'alias_name' : '',
            'password1': '',
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        # 'profile_img', email
        fields = ('real_name','introduce', 'gender', 'is_notify')
      
        widgets = {
            'is_notify': forms.CheckboxInput(),
            'introduce':forms.TextInput(attrs={"placeholder" : "자기소개를 입력하세요"}),
        }
        labels = {
            'gender' : '성별',
            'introduce' : '자기소개',
            'is_notify' : '알림여부',
            # 'password' : '비밀번호',
        }


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=100,
        label='',
        widget=forms.TextInput(attrs={'placeholder': '가입한 핸드폰번호/이메일 입력'})
    )
    password = forms.CharField(
        max_length=100,
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': '비밀번호'})
    )

instagram_clone/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView

from .models import User
from notifications.models import Notification
from posts.models import Post
from django.db.models import Q

from django.contrib.auth import login as auth_login
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import logout as auth_logout
from django.http import JsonResponse

from django.core.files.storage import default_storage
from django.utils.datastructures import MultiValueDictKeyError

from django.contrib.auth.hashers import check_password


@login_required
def change_pw(request, user_idx):
    user = get_object_or_404(User, pk=user_idx)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user.set_password(form.cleaned_data['new_password1'])
            user.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:profile', user.idx)
    else:
        form = PasswordChangeForm(request.user)
    return redirect('accounts:profile', user_idx=user_idx)


@login_required
def index(request, user_idx):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    user = User.objects.get(pk=user_idx)
    # 사용자가 작성한 게시글 가져오기
    user_posts = Post.objects.filter(user=user)
        
    # 팔로잉 및 팔로워 수 계산
    following_count = user.followings.count() 
    follower_count = user.followers.count()   

    context = {
        'user': user,
        'following_count': following_count,
        'follower_count': follower_count,
        'user_posts': user_posts,  # 사용자가 작성한 게시글을 컨텍스트에 추가

    } 

    return render(request, 'accounts/index.html', context)


import json
from django.http import JsonResponse

# 개인 프로파일 화면 (편집모드로 띄우기)
@login_required
def profile(request, user_idx):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    user = get_object_or_404(User, pk=user_idx)
    
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            user.introduce = form.cleaned_data['introduce']
            user.gender = form.cleaned_data['gender']
            user.save()
            return redirect('accounts:profile', user.id)
    else:
        form = CustomUserChangeForm(instance=user)
    
    context = {
        'form': form,
        'user': user,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def profile(request, user_idx):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    user = get_object_or_404(User, pk=user_idx)
    
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', user.id)
    else:
        form = CustomUserChangeForm(instance=user)
    
    context = {
        'form': form,
        'user': user
    }
    return render(request, 'accounts/profile.html', context)




# 개인 프로파일 화면 (편집모드로 띄우기)
def old_profile(request, user_idx):
    # 사용자 정보 가져오기
    user = User.objects.get(pk=user_idx)
    # 사용자가 작성한 게시글 가져오기
    user_posts = Post.objects.filter(user=user)
    # 팔로잉 및 팔로워 수 계산
    following_count = user.followings.count() 
    follower_count = user.followers.count()   

    # 사용자가 로그인되어 있는지 확인
    if not request.user.is_authenticated:
        return redirect('accounts:login')
  

    context = {
        'user': user,
        'following_count': following_count,
        'follower_count': follower_count,
        'user_posts': user_posts,  # 사용자가 작성한 게시글을 컨텍스트에 추가

    } 


    return render(request, 'accounts/profile.html', context) 


# 사진 업로드
@login_required
def upload_img(request, user_idx):
    user = get_object_or_404(User, pk=user_idx)
    if 'profile_img' in request.FILES:
        file = request.FILES['profile_img']
        filename = default_storage.save(file.name, file)
        file_url = default_storage.url(filename)
        user.profile_url = file_url
        user.save()
    return redirect('accounts:profile', user.id)

@login_required
def delete_img(request, user_idx):
    user = get_object_or_404(User, pk=user_idx)
    if user.profile_url:
        default_storage.delete(user.profile_url)
        user.profile_url = ''
        user.save()
    return redirect('accounts:profile', user.id)

def signup(request):
    # 이미 로그인한 경우, 회원가입 로직 실행 막기
    if request.user.is_authenticated:
        return redirect('accounts:profile', request.user.id)
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        print(request)

        if form.is_valid():
            form.save()
 
            return redirect('accounts:login')
        else:
            print(form.errors)
            return redirect('accounts:signup')
    else:
        form = CustomUserCreationForm()
        context = {
            'form':form
        }
    return render(request, 'accounts/signup.html', context)


from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import LoginForm


def login(request):
    # 이미 로그인한 경우, 정보화면으로 이동
    if request.user.is_authenticated:
        return redirect('accounts:index', request.user.id)
    
    # 로그인 시도
    # 세션을 생성! 하니까 POST
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            print(request.user.id)
            return redirect('accounts:index', request.user.id)

    form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def search(request):
    searched_users = None
    searched_posts = None
    search_keyword = request.GET.get('search_keyword')
    
    if search_keyword:
        if search_keyword.startswith('#'):  # 해시태그인 경우
            searched_posts = Post.objects.filter(
                content__icontains=search_keyword
                ).order_by("-created_at")

        else:  # 해시태그가 아닌 경우 유저를 검색
            searched_users = User.objects.filter(
                Q(alias_name__icontains=search_keyword) | 
                Q(real_name__icontains=search_keyword) |
                Q(username__icontains=search_keyword)
            )
            
    context = {
        'searched_users': searched_users, 
        'searched_posts': searched_posts
    } 
    
    return render(request, 'accounts/search.html', context)

@login_required
def follow(request, user_idx):
    user = request.user
    followed_user = User.objects.get(pk=user_idx)
    
    if user in followed_user.followers.all():
        followed_user.followers.remove(user)
    else:
        followed_user.followers.add(user)
        # 새로운 팔로워가 생겼을 때 알림 생성
        # create_newfollower_notification(user, followed_user)
        
    return redirect('accounts:index', user_idx=user_idx)


# logout은 반드시 로그인 상태가 필수조건
@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


# # 이미지 업로드 관련
# def image(request):

#     return render(request, 'sample/index.html')

instagram_clone/accounts/templates/accounts/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Clone</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src='https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js'></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>
<body class='signup_body'>

    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block script %}{% endblock script %}
</body>
</html>

instagram_clone/accounts/templates/accounts/img.html
{% extends "base.html" %}


{% block content %}
<!DOCTYPE html>



{% endblock content %}

{% block script %}
{% endblock script %}

instagram_clone/accounts/templates/accounts/index.html
{% extends "base.html" %}

{% block content %}
<style>
    .instagram-post {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px; /* 패딩을 줄입니다. */
        margin-bottom: 10px;
        background-color: #fff;
        box-shadow: 0px 0px 3px rgba(0, 0, 0, 0.1); /* 그림자를 약간 줄입니다. */
        max-width: 500px; /* 최대 너비를 지정합니다. */
        width: 100%; /* 너비를 100%로 설정하여 부모 요소의 너비에 맞춥니다. */
    }

    .post-body {
        display: flex;
        flex-direction: column;
    }

    .post-header {
        display: flex;
        align-items: center;
        margin-bottom: 10px;
    }

    .profile-image {
        width: 40px;
        height: 40px;
        border-radius: 50%;
        margin-right: 10px;
    }

    .username {
        font-weight: bold;
    }

    .post-content {
        margin-bottom: 10px;
    }

    .post-image {
        max-width: 100%;
        height: auto;
        margin-bottom: 10px;
        border-radius: 5px;
        margin-top: 20px;
    }

    .post-actions {
        display: flex;
        justify-content: space-between;
        
    }

    .comments-section {
        margin-top: 20px;
    }

    .comment-list {
        list-style-type: none;
        padding: 0;
        margin: 0;
    }

    .comment {
        margin-bottom: 10px;
    }

    .comment-form {
        margin-top: 20px;
    }

    .comment-input {
        width: calc(100% - 20px);
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: none;
    }

    .comment-submit-btn {
        margin-top: 10px;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .comment-submit-btn:hover {
        background-color: #0056b3; /* hover 시 색상 변경 */
    }
    /* 댓글 수정, 삭제 버튼의 글자 크기를 줄입니다. */
    .comment-action-link {
        
        color: #007bff; /* 파란색 링크 */
        text-decoration: none;
        font-size: 12px; /* 글자 크기를 조정합니다. */
    }

    /* 댓글 입력란과 댓글 수정, 삭제 버튼을 한 덩이로 묶어줍니다. */
    .comment-controls {
        display: flex;
        flex-direction: column;
    }
    /* 리스트 아이템에서 번호를 표시하지 않도록 설정합니다. */
    .comment-controls li {
        list-style-type: none;
    }
</style>

<h3>계정페이지 관리</h3>

<div style='display: flex; flex-direction: row;'>

    <div style='padding: 5px 5px 5px 5px; '>
    {% if user.profile_url %}
    <img class='index-profile-pic-img' src="{{user.profile_url}}" alt="프로필 사진" height=100>
    {% else %}
    {% load static %}
    <img class='index-profile-pic-img' src="{% static 'images/none_img.jpg' %}" alt="프로필 사진" height=100>
    {% endif %}
    </div>

    <div style='display: flex; flex-direction: column; width:150px; padding: 5px 5px 5px 5px'>
        <span> {{ user.alias_name }} </span>
        <span> </span>
        <span> </span>
    </div>

    <div style='display: flex; flex-direction: column; width:200px; padding: 5px 5px 5px 5px'>
        <span > 
            {% if request.user == user %}
            <a class="btn btn-light text-decoration-none" href='{% url "accounts:profile" user.id %}'>프로필 편집 </a>
            {% else %}
            프로필 편집
            {% endif %}
        </span>
        
        <span> 
        <!--팔로잉/팔로워 보여주기-->
        <p>
            팔로잉 수: <a class="text-decoration-none" href="#" onclick="showFollowingList()">{{ following_count }}</a>
        </p>
        <div id="following_popup" style="display: none;">
            <p>팔로잉 목록</p>
            <ul>
                {% for following_user in user.followings.all %}
                    <li><a class="btn btn-light text-decoration-none"  href="{% url 'accounts:index' user_idx=following_user.id %}">{{ following_user.username }}</a></li>
                {% endfor %}
            </ul>
        </div>   

        <!--팔로우 버튼-->
        {% if request.user != user %}
        <form action="{% url 'accounts:follow' user_idx=user.id %}" method="POST">
            {% csrf_token %}
            {% if request.user in user.followers.all %}
                <input type="submit" value="UnFollow">
            {% else %}
                <input type="submit" value="Follow">
            {% endif %}
        </form>
        {% endif %}  
       </span>        
    </div>

    <div style='display: flex; flex-direction: column; width:150px; padding: 5px 5px 5px 5px'>
        <!-- add_box id 속성 추가 -->
        <span>
            {% if request.user == user %}
            <a class="btn btn-light text-decoration-none" href="{% url "accounts:logout" %}">로그아웃</a>
            {% else %}
            로그아웃
            {% endif %} 
        </span>
        <span>
            <p>팔로워 수: <a class="text-decoration-none" href="#" onclick="showFollowerList()">{{ follower_count }}</a></p>
            <div id="follower_popup" style="display: none;">
                <p>팔로워 목록</p>
                <ul>
                    {% for follower_user in user.followers.all %}
                        <li><a class="btn btn-light text-decoration-none" href="{% url 'accounts:index' user_idx=follower_user.id %}">{{ follower_user.username }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </span>
    </div>

    <div style='display: flex; flex-direction: column; width:150px; padding: 5px 5px 5px 5px'>
        <!-- 보관함으로 이동 링크 -->
        {% if request.user == user %}
        <span>
            <a class="btn btn-light text-decoration-none" href="{% url 'stories:archive' %}">보관함으로<br>이동</a>
        </span>
        {% endif %}
    </div>
</div>

<!-- 사용자가 작성한 글 목록 -->
<h4>내가 작성한 글 목록</h4>
<hr>

<div style='width:600px; '>
<div class="container justify-content-start align-items-start" >
    <div class="row flex-wrap">
      {% for post in user_posts %}
      
        <div class=" col-4 px-1 d-flex  mt-1">
            <div style='width:600px;' class="square-container align-items-left">
            <a href="{% url "posts:detail" post.id %}"><img class="img-fluid resize_img" src="{{ post.image}}" alt=""></a>
            </div>
     </div>
      {% endfor %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    // 팔로잉 목록 보여주는 함수
    function showFollowingList() {
        var followingPopup = document.getElementById("following_popup");
        var followerPopup = document.getElementById("follower_popup");
        if (followingPopup.style.display === "none") {
            followingPopup.style.display = "block";
            followerPopup.style.display = "none"; // 다른 팝업은 숨깁니다.
        } else {
            followingPopup.style.display = "none";
        }
    }

    // 팔로워 목록 보여주는 함수
    function showFollowerList() {
        var followerPopup = document.getElementById("follower_popup");
        var followingPopup = document.getElementById("following_popup");
        if (followerPopup.style.display === "none") {
            followerPopup.style.display = "block";
            followingPopup.style.display = "none"; // 다른 팝업은 숨깁니다.
        } else {
            followerPopup.style.display = "none";
        }
    }

    window.addEventListener('load', function() {
        var images = document.querySelectorAll('.resize_img');
        images.forEach(function(image) {
            // 이미지의 가로와 세로 비율을 계산
            var aspectRatio = image.width / image.height;
            if (aspectRatio > 1) {
                // 가로가 세로보다 긴 경우
                image.style.width = '100%';
                image.style.height = '100%';

            } else {
                // 세로가 가로보다 긴 경우
                image.style.width = '100%';
                image.style.height = '100%';
            }
        });
    });

</script>
{% endblock script %}

instagram_clone/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h3>{{ user.real_name }} 프로필 페이지</h3>

<!--기타 정보-->
<p>자기소개: {{ user.introduce }}</p>
<p>성별:
    {% if user.gender == 'F' %}
        여자
    {% elif user.gender == 'M' %}
        남자
    {% else %}
        선택안함
    {% endif %}
</p>

{% if user.profile_url %}
<div class="profile-pic">
    <img src="{{ user.profile_url }}" alt="프로필 사진" style="max-width: 10%;">
</div>
{% else %}
<div class="account-profile-pic">
    <img src="{% static 'images/none_img.jpg' %}" alt="프로필 사진" width="50px"> 
</div>
<p>프로필 사진을 등록하세요.</p>
{% endif %}

<div>
<!-- add_box id 속성 추가 -->
<button id="img_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#imgModalCenter" style="width: 150px;">
    사진변경
</button>

<!-- model id 속성 추가 -->
<!-- create feed -->
<div class="modal fade" id="imgModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">사진 변경</h5>
            </div>
            <div class="modal-body">

                <form method="post" action="{% url "accounts:upload_img" user.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="profile_img">
                <button type="submit" value='사진올리기' class='btn btn-primary btn-sm'>Upload</button>
                </form>

                <p>
                <form class='delete_img' method='post' action="{% url "accounts:delete_img" user.id %}">
                    {% csrf_token %}
                    <button type="submit" value='사진삭제' class='btn btn-primary btn-sm'>현재 사진 삭제</button>
                </form></p>
            </div>

            <div class="modal-footer">
                <button id="img_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>




<!-- Button trigger modal -->
<button id="pro_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#ProfileModalCenter" style="width: 150px;">
    프로필변경
</button>

<!-- Modal -->
<div class="modal fade" id="ProfileModalCenter" tabindex="-1" role="dialog" aria-labelledby="ProfileModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">프로필 편집</h5>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'accounts:profile' user.id %}">
                    {% csrf_token %}
                    <table>
                        <tbody>
                            <tr>
                                <td>자기소개</td>
                                <td><input id="intro" type="text" size="40" placeholder="자기소개를 입력하세요" name="introduce" value="{{ user.introduce }}"></td>
                            </tr>
                            <tr>
                                <td>성별</td>
                                <td>
                                    <select id="gender" name="gender">
                                        <option value="M" {% if user.gender == 'M' %} selected {% endif %}>남성</option>
                                        <option value="F" {% if user.gender == 'F' %} selected {% endif %}>여성</option>
                                        <option value="O" {% if user.gender == 'O' %} selected {% endif %}>선택안함</option>
                                    </select>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <br>
                    <div class="modal-footer">
                        <button class="btn btn-primary"  type="submit">저장</button>
                        <button id="pro_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

<!-- 비밀번호 변경 모달 -->
<button id="pw_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#PasswordModalCenter" style="width: 150px;">
    비밀번호 변경
</button>

<div class="modal fade" id="PasswordModalCenter" tabindex="-1" role="dialog" aria-labelledby="PasswordModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="PasswordModalLongTitle">비밀번호 변경</h5>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'accounts:change_pw' user.id %}">
                    {% csrf_token %}
                    <table style=' border: 1px '>
                        <tbody>
                            <tr>
                                <td>현재 비밀번호</td>
                                <td><input id="current_password" type="password" size="40" placeholder="현재 비밀번호를 입력하세요" name="current_password"></td>
                            </tr>
                            <tr>
                                <td>새로운 비밀번호</td>
                                <td><input id="new_password1" type="password" size="40" placeholder="새로운 비밀번호를 입력하세요" name="new_password1"></td>
                            </tr>
                            <tr>
                                <td>새로운 비밀번호 확인</td>
                                <td><input id="new_password2" type="password" size="40" placeholder="새로운 비밀번호를 다시 입력하세요" name="new_password2"></td>
                            </tr>
                        </tbody>
                    </table>

                    <br>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">변경</button>
                        <button id="pw_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

</div>

{% endblock content %}

{% block script %}
<script>
    // 프로필 편집 클릭
    document.querySelector('#pro_modal').addEventListener('click', function() {
        $('#ProfileModalCenter').modal('show');
    });
    // 프로필 편집 닫기
    document.querySelector('#pro_close').addEventListener('click', function() {
        $('#ProfileModalCenter').modal('hide');
    });
    // 비밀번호 변경 클릭
    document.querySelector('#pw_modal').addEventListener('click', function() {
        $('#PasswordModalCenter').modal('show');
    });
    // 비밀번호 변경 닫기
    document.querySelector('#pw_close').addEventListener('click', function() {
        $('#PasswordModalCenter').modal('hide');
    });
        // 사진편집 변경 클릭
        document.querySelector('#img_modal').addEventListener('click', function() {
            $('#imgModalCenter').modal('show');
        });
        // 사진편집 변경 닫기
        document.querySelector('#img_close').addEventListener('click', function() {
            $('#imgModalCenter').modal('hide');
        });
</script>
{% endblock script %}