instagram_clone/posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),
    
    path('create/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    
    path('detail/<int:pk>', views.detail, name='detail'),
    path('like/<int:post_id>/', views.post_like, name='post_like'),
    
    path('delete_comment/<int:post_id>/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('create_comment/<int:pk>', views.create_comment, name='create_comment'),
    path('edit_comment/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('user_posts/', views.user_posts, name='user_posts'),
]

instagram_clone/stories/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'stories'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('story_delete/<int:pk>/', views.story_delete, name='story_delete'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('archive/', views.archive, name='archive'),
]

instagram_clone/stories/models.py
from django.db import models
from accounts.models import User
from django.utils import timezone

class Story(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='stories/')
    created_at = models.DateTimeField(default=timezone.now)

instagram_clone/stories/forms.py
from django import forms
from .models import Story

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['image']

    def clean_image(self):
        image = self.cleaned_data.get('image')
        return image

instagram_clone/stories/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Story
from .forms import StoryForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import FileResponse
from django.conf import settings
from django.core.files.storage import default_storage
from django.utils import timezone
from datetime import timedelta

@login_required
def create(request):
    print(request.method)
    if request.method == 'POST':
        form = StoryForm(request.POST, request.FILES)
        print(form.is_valid())
        if form.is_valid():
            story = form.save(commit=False)
            story.user = request.user 
            story.save()
            
            # 파일을 S3에 업로드
            file = request.FILES['image']
            filename = default_storage.save(file.name, file)
            file_url = default_storage.url(filename)
            print(filename, file_url)

            # return redirect('stories:detail', pk=story.pk)  # 상세 페이지로 리디렉션
            return redirect('posts:home')  # 상세 페이지로 리디렉션

        else:
            print(form.errors)
    else:
        form = StoryForm()
    return render(request, 'stories/create.html', {'form': form})

def detail(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    user_stories = Story.objects.filter(user=user)

    context = {
        'user': user,
        'user_stories': user_stories,
    }
    return render(request, 'stories/detail.html', context)

# 상세 페이지 열기
def edit(request, pk):
    # user = get_object_or_404(get_user_model(), pk=pk)
    story = Story.objects.get(pk=pk)

    context = {
        'story': story,
    }
    return render(request, 'stories/edit.html', context)


@login_required
def delete(request, pk):
    story = get_object_or_404(Story, pk=pk)
    story.is_expired = True
    story.save()
    return redirect('post:home')

def story_delete(request, pk):
    story = get_object_or_404(Story, pk=pk)
    if request.user == story.user:
        story.delete()

    # 바로 인덱스 페이지로 리다이렉트합니다.
    return redirect('stories:archive')
    

@login_required
def archive(request):
    user = request.user
    # archived_stories = Story.objects.filter(created_at__lte=timezone.now() - timezone.timedelta(days=1), user=user)
    # 테스트를 위해 10초로 변경
    archived_stories = Story.objects.filter(created_at__lte=timezone.now() - timedelta(seconds=10), user=user)
    return render(request, 'stories/archive.html', {'archived_stories': archived_stories})

instagram_clone/stories/templates/stories/archive.html
{% extends "base.html" %}

{% block content %}
<h3>보관함</h3>

{% if archived_stories %}

<div style='width:600px; '>
    <div class="container  justify-content-start align-items-start">
        <div class="row flex-wrap">
            {% for story in archived_stories %}
                <div class="col-4 px-1 d-flex mt-1">
                    <div style='width:600px;' class="square-container align-items-left">
                    <a href="{% url "stories:edit" story.id %}"><img src="{{ story.image.url }}" class="img-fluid resize_img" style='width:600px;'></a>
                    </div>

                </div>
                {% if forloop.counter|divisibleby:3 and not forloop.last %}
                    </div><div class="row justify-content-center">
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% else %}
    <p>보관함에 아무런 스토리가 없습니다.</p>
{% endif %}

{% endblock content %}

{% block script %}
<script>
    window.addEventListener('load', function() {
        var images = document.querySelectorAll('.resize_img');
        images.forEach(function(image) {
            // 이미지의 가로와 세로 비율을 계산
            var aspectRatio = image.width / image.height;
            if (aspectRatio > 1) {
                // 가로가 세로보다 긴 경우
                image.style.width = '100%';
                image.style.height = '100%';

            } else {
                // 세로가 가로보다 긴 경우
                image.style.width = '100%';
                image.style.height = '100%';
            }
        });
    });

</script>

{% endblock script %}

instagram_clone/stories/templates/stories/create.html
{% extends "base.html" %}
{% block content %}
{% comment %} <h1>Upload Story</h1> {% endcomment %}
{% comment %} <form method="POST" action="{% url "stories:create" %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="image">
    <button type="submit">Upload</button>
</form> {% endcomment %}


<style>
    .text-right {
        text-align: right;
    }
</style>
    <div class="container mt-8">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">새 스토리 만들기</div>
                    <div class="card-body">
                        <form id="post_form" action='{% url "stories:create" %}' method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="image_input"></label>
                                <input type="file" class="form-control-file" id="image_input" name="image" accept="image/*" onchange="previewImage(event)">
                            </div>
                            <div class="form-group" style="margin-top: 10px;"> <!-- 여기에 공백 추가 -->
                                <img id="image_preview" src="#" alt="이미지 미리보기" style="display: none; max-width: 100%; max-height: 350px;">
                            </div>
                            <div class="text-right"> <!-- 버튼을 오른쪽에 배치하기 위해 text-right 클래스 추가 -->
                                <button type="submit" class="btn btn-primary" style="margin-top: 10px;">공유하기</button> <!-- 여기에 공백 추가 -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}
{% block script %}
<script>
    function previewImage(event) {
        const image = document.getElementById('image_preview');
        image.style.display = 'block';
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>
{% endblock script %}

instagram_clone/stories/templates/stories/detail.html
{% extends 'base.html' %}
{% block content %}
<br>
<h3>[ {{user.alias_name}}님의 스토리 목록 ]</h3>

{% if user_stories %}

<div style='width:600px;'>
    <div class="container  justify-content-start align-items-start">
        <div class="row flex-wrap">
                
        {% for story in user_stories %}

        <div class="col-4 px-1 d-flex mt-1">
            <div class="square-container align-items-left">
            <img src="{{ story.image.url }}" class="img-fluid resize_img" style='width:600px;'>
            </div>
        </div>

        {% endfor %}
    </ul>
{% else %}
    <p>현재 업로드된 스토리가 없습니다.</p>
    <a href="{% url 'stories:create' %}">스토리 업로드하기</a>
{% endif %}
{% endblock content %}

{% block script %}
<script>
    window.addEventListener('load', function() {
        var images = document.querySelectorAll('.resize_img');
        images.forEach(function(image) {
            // 이미지의 가로와 세로 비율을 계산
            var aspectRatio = image.width / image.height;
            if (aspectRatio > 1) {
                // 가로가 세로보다 긴 경우
                image.style.width = '100%';
                image.style.height = '100%';

            } else {
                // 세로가 가로보다 긴 경우
                image.style.width = '100%';
                image.style.height = '100%';
            }
        });
    });

</script>

{% endblock script %}

instagram_clone/stories/templates/stories/edit.html
{% extends 'base.html' %}
{% block content %}
<br>
<h3>[ 스토리 상세페이지 ]</h3>

    <div width=300px class="text-right"> 
        <div >
            <img width=300px src="{{ story.image.url }}" class="img-fluid" style='width:300px;'>
        </div>
        <br>
        <div class="text-right">
            <a href='#' onclick="confirmDeleteStory('{{ story.pk }}')" class="btn btn-sm btn-light  text-decoration-none">삭제</a>
        </div>
        
    </div>
{% endblock content %}
{% block script %}
<script>
        function confirmDeleteStory(postId) {
            if (confirm("정말로 삭제하시겠습니까?")) {
                window.location.href = "{% url 'stories:story_delete' pk=story.pk %}";
            }
        }
</script>
{% endblock script %}