instagram_clone/accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('accounts/', views.profile, name='profile'),
    path('index/<int:user_idx>', views.index, name='index'),
    path('', views.profile, name='profile'),
    
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
    path('upload_img/<int:user_idx>', views.upload_img, name='upload_img'),
    path('delete_img/<int:user_idx>', views.delete_img, name='delete_img'),
    path('profile/<int:user_idx>', views.profile, name='profile'),
    path('change_pw/<int:user_idx>', views.change_pw, name='change_pw'),
   
    path('search/', views.search, name='search'),
    path('follow/<int:user_idx>', views.follow, name='follow'),
]

instagram_clone/posts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),
    
    path('create/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    
    path('detail/<int:pk>', views.detail, name='detail'),
    path('like/<int:post_id>/', views.post_like, name='post_like'),
    
    path('delete_comment/<int:post_id>/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('create_comment/<int:pk>', views.create_comment, name='create_comment'),
    path('edit_comment/<int:pk>/', views.edit_comment, name='edit_comment'),
    path('user_posts/', views.user_posts, name='user_posts'),
]

instagram_clone/stories/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'stories'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit'),
    path('story_delete/<int:pk>/', views.story_delete, name='story_delete'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('archive/', views.archive, name='archive'),
]

instagram_clone/posts/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    image = models.ImageField(upload_to='images/', max_length=1000)  # 이미지 필드를 선택적으로 만듦
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts', through='PostLikeUsers')
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PostLikeUsers(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    memo = models.TextField(null=True)

    class Meta:
        db_table = 'post_like_users'

instagram_clone/posts/forms.py
from .models import Post, Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']
        widgets = {
           
            'content': forms.Textarea(attrs={'class': 'my-class'})
        }
        error_messages = {
            'title': {
                'max_length': '입력 길이를 초과했습니다.'
            }
        }
        
        # 모든 필드를 사용
        # fields = '__all__'

        # 지정 필드만 사용
        # fields = ['content']

        # 특정 필드 제외
        # exclude = ['title']

        # fields = ['title', 'content']
        

instagram_clone/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from .models import Post, Comment
from accounts.models import User
from stories.models import Story
from notifications.models import Notification
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.utils.datastructures import MultiValueDictKeyError
from django.db.models import Q
from django.utils import timezone
from datetime import timedelta
from django.db.models import Count

from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST

@login_required
def home(request):
    user = get_object_or_404(User, pk=request.user.id)
    
    # 현재 로그인한 사용자가 팔로우한 사용자들의 목록
    followings = user.followings.all()

    # 필터링 조건
    filter_condition = (
        Q(user__in=followings) | Q(user=user)
    ) & Q(created_at__gte=timezone.now() - timedelta(days=1))

    # 필터링된 결과를 사용하여 그루핑 및 어노테이션 적용
    user_grouped_stories = (
        Story.objects
        .filter(filter_condition)
        .values('user__id', 'user__username', 'user__profile_url', 'user__alias_name')
        .annotate(num_stories=Count('id'))
    )
    
    # 포스트들을 가져오고, 시간을 계산하여 context에 추가
    posts = Post.objects.filter(
        Q(user__in=followings) | Q(user=user)
    ).order_by("-created_at")

    # 시간 변수를 리스트로 초기화
    time_since_created_list = []

    for post in posts:
        # 현재 시간과 포스트 작성 시간의 차이를 계산
        time_difference = timezone.now() - post.created_at
        if time_difference < timedelta(minutes=1):
            seconds_since_created = int(time_difference.total_seconds())
            time_since_created = f"{seconds_since_created}초 전"
        elif time_difference < timedelta(hours=1):
            minutes_since_created = int(time_difference.total_seconds() // 60)
            time_since_created = f"{minutes_since_created}분 전"
        elif time_difference < timedelta(days=1):
            hours_since_created = int(time_difference.total_seconds() // 3600)
            time_since_created = f"{hours_since_created}시간 전"
        else:
            days_since_created = int(time_difference.total_seconds() // 86400)
            time_since_created = f"{days_since_created}일 전"
        
        # 각 포스트의 시간을 리스트에 추가
        time_since_created_list.append(time_since_created)
        
    posts_with_time = list(zip(posts, time_since_created_list))
    
    # 게시물별로 시간을 저장한 리스트를 context에 추가
    context = {
        'user': user,
        'posts_with_time': posts_with_time,
        'user_grouped_stories': user_grouped_stories,
    }
    return render(request, 'posts/home.html', context)



@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            # 이미지를 S3에 업로드
            if 'image' in request.FILES:
                image = request.FILES['image']
                filename = default_storage.save(image.name, image)
                image_url = default_storage.url(filename)
            else:
                image_url = None

            # 이미지를 S3에 업로드
            if 'image' in request.FILES:
                image = request.FILES['image']
                filename = default_storage.save(image.name, image)
                image_url = default_storage.url(filename)
            else:
                image_url = None

            post = form.save(commit=False)
            post.user = request.user
            post.image = image_url  # 이미지 URL을 모델에 저장
            post.image = image_url  # 이미지 URL을 모델에 저장
            post.save()
            return redirect('posts:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'posts/create.html', {'form': form})

@login_required
def update(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user != post.user:
        return redirect('posts:home')
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)  # request.FILES 추가
        form = PostForm(request.POST, request.FILES, instance=post)  # request.FILES 추가
        if form.is_valid():
            # 이미지를 S3에 업로드
            if 'image' in request.FILES:
                image = request.FILES['image']
                filename = default_storage.save(image.name, image)
                image_url = default_storage.url(filename)
                post.image = image_url  # 이미지 URL을 모델에 저장

            # 이미지를 S3에 업로드
            if 'image' in request.FILES:
                image = request.FILES['image']
                filename = default_storage.save(image.name, image)
                image_url = default_storage.url(filename)
                post.image = image_url  # 이미지 URL을 모델에 저장

            form.save()
            return redirect('posts:detail', post.pk)
        
        
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
        'post': post
    }
    return render(request, 'posts/update.html', context)

def detail(request, pk):
    post = Post.objects.get(pk=pk)
    comments = post.comments.all()
    comment_form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'posts/detail.html', context)

def delete(request, pk):
    post = Post.objects.get(pk=pk)
    if request.user == post.user:
        post.delete()

    
    # 바로 인덱스 페이지로 리다이렉트합니다.
    return redirect(reverse('accounts:index', kwargs={'user_idx': request.user.id}))
    
    # 바로 인덱스 페이지로 리다이렉트합니다.
    return redirect(reverse('accounts:index', kwargs={'user_idx': request.user.id}))

from django.shortcuts import redirect, HttpResponse
from django.contrib import messages

def delete_comment(request, post_id, comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
        if request.user == comment.user:
            comment.delete()
            return redirect('posts:detail', post_id)
        else:
            # Display an error message if the user is not the owner of the comment
            messages.error(request, "You don't have permission to delete this comment.")
            return redirect('posts:detail', post_id)
    except Comment.DoesNotExist:
        # Display an error message if the comment does not exist
        messages.error(request, "The comment you're trying to delete does not exist.")
        return redirect('posts:detail', post_id)


def create_comment_notification(user, post, comment_content):
    message = f'{user.real_name}님이 회원님의 게시물에 댓글을 남겼습니다: {comment_content}'
    Notification.objects.create(user=post.user, message=message, post=post, msg_user_id=user.id, msg_user_real_name=user.real_name)


def create_comment(request, pk):
    referring_url = request.META.get('HTTP_REFERER')

    if request.method == 'POST':
        content = request.POST.get('content')
        if content:
            post = Post.objects.get(pk=pk)
            comment = Comment.objects.create(post=post, user=request.user, content=content)

            # 댓글이 작성되었을 때 알림 생성
            create_comment_notification(request.user, post, content)


    return HttpResponseRedirect(referring_url) if referring_url else redirect('posts:home')


@require_POST
def edit_comment(request, pk):
    referring_url = request.META.get('HTTP_REFERER')
    comment = Comment.objects.get(pk=pk)
    form = CommentForm(request.POST, instance=comment)
    
    if form.is_valid():
        form.save()

    return HttpResponseRedirect(referring_url) if referring_url else redirect('posts:home')

        

def create_like_notification(user, post):
    message = f'{user.real_name}님이 회원님의 게시물을 좋아합니다.'
    # Notification.objects.create(user=post.user, message=message, post=post)
    Notification.objects.create(user=post.user, message=message, post=post, msg_user_id=user.id, msg_user_real_name=user.real_name)

def post_like(request, post_id):
    referring_url = request.META.get('HTTP_REFERER')
    
    post = Post.objects.get(pk=post_id)
    # 이미 좋아요를 한 사람의 경우에는 좋아요를 취소
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user, through_defaults={'memo': '메모'})
        # 좋아요 알림 생성
        create_like_notification(request.user, post)
    return HttpResponseRedirect(referring_url) if referring_url else redirect('posts:home')

def user_posts(request):
    # 현재 사용자가 작성한 모든 글을 가져옴
    user_posts = Post.objects.filter(user=request.user)
    return render(request, 'posts/user_posts.html', {'user_posts': user_posts})

instagram_clone/posts/templates/posts/create.html
{% extends "base.html" %}

{% block content %}
<style>
    .text-right {
        text-align: right;
    }
</style>
    <div class="container mt-8">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">새 게시물 만들기</div>
                    <div class="card-body">
                        <form id="post_form" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="image_input"></label>
                                <input type="file" class="form-control-file" id="image_input" name="image" accept="image/*" onchange="previewImage(event)">
                            </div>
                            <div class="form-group" style="margin-top: 10px;"> <!-- 여기에 공백 추가 -->
                                <img id="image_preview" src="#" alt="이미지 미리보기" style="display: none; max-width: 100%; max-height: 350px;">
                            </div>
                            <div class="form-group" style="margin-top: 10px;"> <!-- 여기에 공백 추가 -->
                                <label for="content"></label>
                                <textarea class="form-control" id="content" name="content" required></textarea>
                            </div>
                            <div class="text-right"> <!-- 버튼을 오른쪽에 배치하기 위해 text-right 클래스 추가 -->
                                <button type="submit" class="btn btn-primary" style="margin-top: 10px;">공유하기</button> <!-- 여기에 공백 추가 -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    function previewImage(event) {
        const image = document.getElementById('image_preview');
        image.style.display = 'block';
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>
{% endblock script %}

instagram_clone/posts/templates/posts/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="posts">
    <div class="post-home">
        <div class="info">
            <div class="user">
                <a href="{% url 'accounts:index' post.user.id %}" class="link-dark text-decoration-none">
                    <div class="profile-pic">
                        {% if post.user.profile_url %}
                        <img src="{{ post.user.profile_url }}" alt="프로필 사진">
                        {% else %}
                        <img src="{% static 'images/none_img.jpg' %}" alt="프로필 사진">
                        {% endif %}
                    </div>
                    <p class="username">{{ post.user.username }}</p>
                </a>
                <p class="username"></p>
            </div>
        </div>
        <img src="{{ post.image }}" class="post-image" alt="">
        <div class="post-content">
            <!-- 좋아요 버튼 -->
            <form action="{% url 'posts:post_like' post_id=post.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in post.like_users.all %}
                <button type="submit" class="btn btn-transparent p-0"><i class="bi bi-heart-fill"></i></button>
                {% else %}
                    <button type="submit" class="btn btn-transparent p-0"><i class="bi bi-heart"></i></button>
                {% endif %}
            </form>
            <strong><p class="likes">좋아요 {{ post.like_users.count }}개</p></strong>
            <p class="description"><span><strong>{{ post.user.username }}</strong></span> {{ post.content }}</p>
        </div>
        
        {% if request.user == post.user %}
        <div class="d-flex justify-content-end">
            <a href='{% url "posts:update" pk=post.pk %}' class="btn btn-light btn-sm text-decoration-none">수정</a>
            &nbsp;
            <a href='#' onclick="confirmDeletePost('{{ post.pk }}')" class="btn btn-sm btn-light text-decoration-none">삭제</a>
        </div>
        {% endif %}
        <div class="comment-wrapper">
            <strong><p>댓글 ({{ post.comments.all|length }})</p></strong>
            <ul class="list-group">
                {% for comment in post.comments.all %}
                    <li class="list-group-item">
                        <div id="comment-{{ comment.pk }}" class="d-flex justify-content-between"> <!-- 수정한 부분 -->
                            <div>
                                <strong>{{ comment.user.username }}</strong> 
                                <span id="comment-content-{{ comment.pk }}">{{ comment.content }}</span>
                            </div>
                            {% if request.user == comment.user %}
                            <span> <!-- 수정한 부분 -->
                                {% csrf_token %}
                                <button class="btn btn-light btn-sm text-decoration-none" id="edit-comment-btn" data-comment-id="{{ comment.pk }}">수정</button>
                                <button class="btn btn-light btn-sm text-decoration-none" id="delete-comment-btn" data-post-id="{{ post.pk }}" data-comment-id="{{ comment.pk }}">삭제</button>
                            </span>
                            {% endif %}
                        </div>
                    </li>
                {% empty %}
                    <li class="list-group-item">댓글이 없습니다.</li>
                {% endfor %}
            </ul>
            <div>
            <form action="{% url 'posts:create_comment' pk=post.pk %}" method="POST" class="mt-3 d-flex justify-content-end">
                {% csrf_token %}
                <div class="form-group" style="width: 90%;"> <!-- 댓글 작성 칸의 너비 조정 -->
                    <textarea name="content" rows="1" class="form-control"></textarea>
                </div>
                &nbsp;
                <button type="submit" class="btn btn-secondary text-decoration-none" style="width: 130px; height: auto;">댓글 작성</button> <!-- 높이를 자동으로 조절 -->
            </form>

</div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
    <script src="{% static 'js/posts/comments.js' %}"></script>
    <script>
      function openModal(modalId) {
        var modal = document.getElementById(modalId);
        modal.style.display = "block";
      }
      function closeModal(modalId) {
        var modal = document.getElementById(modalId);
        modal.style.display = "none";
      }
      function confirmDeletePost(postId){
        // 사용자에게 삭제 여부를 확인하는 확인 대화 상자를 띄웁니다.
        if (confirm("정말로 이 게시물을 삭제하시겠습니까?"))
            // 확인을 클릭한 경우, 삭제를 수행하는 URL로 이동합니다.
            window.location.href = '{% url "posts:delete" post.pk %}'; // 삭제 URL에 postId를 전달합니다.
      }
    </script>
{% endblock script %}

instagram_clone/posts/templates/posts/user_posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
.post-image {
    width: calc(260px - 2px); /* 이미지 너비 설정 */
    height: calc(260px - 2px); /* 이미지 높이 설정 */
    margin-right: 1px; /* 이미지 사이 간격 설정 */
    margin-bottom: 5px; /* 이미지 아래 간격 설정 */
    display: inline-block; /* 이미지를 인라인 요소로 표시하여 나란히 정렬 */
}

.modal_overlay {
    width: 100%;
    height: 100%;
    position: absolute;
    left: 0;
    top: 0;
    display: none;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background: rgba(0, 0, 0, 0.8);
    backdrop-filter: blur(1.5px);
    -webkit-backdrop-filter: blur(1.5px);
}

.modal_window {
    background: white;
    backdrop-filter: blur(13.5px);
    -webkit-backdrop-filter: blur(13.5px);
    border-radius: 10px;
    border: 1px solid rgba(255, 255, 255, 0.18);
    width: 1000px;
    height: 600px;
    position: relative;
    padding: 10px;
}

.img_upload_space img {
    max-width: 100%;
    max-height: 100%;
}

.modal_content {
    display: flex;
    width: 100%;
    height: 100%;
}

.image_section {
    width: 50%;
    height: 100%;
}

.image_section img {
    max-width: 100%;
    max-height: 100%;
}

.info_section {
    position: absolute;
    top: 0;
    right: 0;
    width: 50%;
    height: 100%;
    overflow: auto; /* 내용이 넘칠 경우 스크롤 표시 */
}

.modal_close {
    cursor: pointer;
    display: flex;
    justify-content: flex-end;
}

</style>

<h3>{{ user.real_name }}</h3>

<!--기타 정보-->
<p>자기소개: {{ user.introduce }}</p>
<p>성별:
    {% if user.gender == 'F' %}
        여성
    {% elif user.gender == 'M' %}
        남성
    {% else %}
        선택안함
    {% endif %}
</p>

{% if user.profile_url %}
<div class="profile-pic-big">
    <img src="{{ user.profile_url }}" alt="프로필 사진" style="max-width: 10%;">
</div>
{% else %}
<div class="account-profile-pic">
    <img src="{% static 'images/none_img.jpg' %}" alt="프로필 사진" width="50px"> 
</div>
<p>프로필 사진을 등록하세요.</p>
{% endif %}

<div>
<!-- add_box id 속성 추가 -->
<button id="img_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#imgModalCenter" style="width: 150px;">
    사진변경
</button>

<!-- model id 속성 추가 -->
<!-- create feed -->
<div class="modal fade" id="imgModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">사진 변경</h5>
            </div>
            <div class="modal-body">

                <form method="post" action="{% url "accounts:upload_img" user.id %}" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="profile_img">
                <button type="submit" value='사진올리기' class='btn btn-primary btn-sm'>Upload</button>
                </form>

                <p>
                <form class='delete_img' method='post' action="{% url "accounts:delete_img" user.id %}">
                    {% csrf_token %}
                    <button type="submit" value='사진삭제' class='btn btn-primary btn-sm'>현재 사진 삭제</button>
                </form></p>
            </div>

            <div class="modal-footer">
                <button id="img_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>




<!-- Button trigger modal -->
<button id="pro_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#ProfileModalCenter" style="width: 150px;">
    프로필변경
</button>

<!-- Modal -->
<div class="modal fade" id="ProfileModalCenter" tabindex="-1" role="dialog" aria-labelledby="ProfileModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">프로필 편집</h5>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'accounts:profile' user.id %}">
                    {% csrf_token %}
                    <table>
                        <tbody>
                            <tr>
                                <td>자기소개</td>
                                <td><input id="intro" type="text" size="40" placeholder="자기소개를 입력하세요" name="introduce" value="{{ user.introduce }}"></td>
                            </tr>
                            <tr>
                                <td>성별</td>
                                <td>
                                    <select id="gender" name="gender">
                                        <option value="M" {% if user.gender == 'M' %} selected {% endif %}>남성</option>
                                        <option value="F" {% if user.gender == 'F' %} selected {% endif %}>여성</option>
                                        <option value="O" {% if user.gender == 'O' %} selected {% endif %}>선택안함</option>
                                    </select>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <br>
                    <div class="modal-footer">
                        <button class="btn btn-primary"  type="submit">저장</button>
                        <button id="pro_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>

                </form>
            </div>

        </div>
    </div>
</div>

<!-- 비밀번호 변경 모달 -->
<button id="pw_modal" type="button" class="btn btn-primary" data-toggle="modal" data-target="#PasswordModalCenter" style="width: 150px;">
    비밀번호 변경
</button>

<div class="modal fade" id="PasswordModalCenter" tabindex="-1" role="dialog" aria-labelledby="PasswordModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="PasswordModalLongTitle">비밀번호 변경</h5>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'accounts:change_pw' user.id %}">
                    {% csrf_token %}
                    <table style=' border: 1px '>
                        <tbody>
                            <tr>
                                <td>현재 비밀번호</td>
                                <td><input id="current_password" type="password" size="40" placeholder="현재 비밀번호를 입력하세요" name="current_password"></td>
                            </tr>
                            <tr>
                                <td>새로운 비밀번호</td>
                                <td><input id="new_password1" type="password" size="40" placeholder="새로운 비밀번호를 입력하세요" name="new_password1"></td>
                            </tr>
                            <tr>
                                <td>새로운 비밀번호 확인</td>
                                <td><input id="new_password2" type="password" size="40" placeholder="새로운 비밀번호를 다시 입력하세요" name="new_password2"></td>
                            </tr>
                        </tbody>
                    </table>

                    <br>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">변경</button>
                        <button id="pw_close" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

</div>
<hr>
<div style="text-align: center;">
    {% for post in user_posts %}
        {% if forloop.counter0|divisibleby:3 %}
            <br> <!-- 3개의 이미지를 표시한 후 줄 바꿈 -->
        {% endif %}
        <div class="post-image">
            {% if post.image %}
                {% with user_name=post.user.username content=post.content %}
                    <a href="#" class="image-modal-trigger" data-image-url="{{ post.image }}" data-username="{{ user_name }}" data-content="{{ content }}" data-post-pk="{{ post.pk }}">
                        <img src="{{ post.image }}" alt="Post Image" style="width: 260px; height: 260px;">
                    </a>
                {% endwith %}
            {% endif %}
        </div>
    {% endfor %}
</div>

<!-- 모달 -->
<div id="first_modal" class="modal_overlay">
    <div class="modal_window">
        <div class="modal_content">
            <div class="image_section">
                <!-- 이미지 표시 공간 -->
                <img id="modal_image">
            </div>
            <div class="info_section">
                <span class="modal_close material-icons-outlined">close</span>
                <p id="user_name"></p> <!-- 유저 이름 표시 -->
                <hr>
                <p id="post_content"></p> <!-- 포스트 내용 표시 -->
                
            </div>
        </div>
    </div>
</div>

<!-- JavaScript -->
<script>
    $(document).ready(function () {
        $(".image-modal-trigger").click(function (e) {
            e.preventDefault(); // 기본 동작 중단
            var imageUrl = $(this).data('image-url'); // 클릭한 이미지의 URL 가져오기
            var userName = $(this).data('username'); // 클릭한 이미지의 유저 이름 가져오기
            var postContent = $(this).data('content'); // 클릭한 이미지의 포스트 내용 가져오기
    
            // 모달에 이미지, 유저 이름, 글 내용 표시
            $("#modal_image").attr("src", imageUrl);
            $("#user_name").text(userName);
            $("#post_content").text(postContent);
    
            // 모달 표시
            $("#first_modal").css({display: 'flex'});
        });
    
        $(".modal_close").click(function () {
            $('#first_modal').css({display: 'none'});
        });
    });
</script>
{% endblock %}

{% block script %}
<script>
    // 프로필 편집 클릭
    document.querySelector('#pro_modal').addEventListener('click', function() {
        $('#ProfileModalCenter').modal('show');
    });
    // 프로필 편집 닫기
    document.querySelector('#pro_close').addEventListener('click', function() {
        $('#ProfileModalCenter').modal('hide');
    });
    // 비밀번호 변경 클릭
    document.querySelector('#pw_modal').addEventListener('click', function() {
        $('#PasswordModalCenter').modal('show');
    });
    // 비밀번호 변경 닫기
    document.querySelector('#pw_close').addEventListener('click', function() {
        $('#PasswordModalCenter').modal('hide');
    });
    // 사진편집 변경 클릭
    document.querySelector('#img_modal').addEventListener('click', function() {
        $('#imgModalCenter').modal('show');
    });
    // 사진편집 변경 닫기
    document.querySelector('#img_close').addEventListener('click', function() {
        $('#imgModalCenter').modal('hide');
    });
</script>
{% endblock script %}